MASTER_HOST: "{{ groups.masters[0] }}"
ETCD_ENDPOINTS: "{{ groups.masters|map('regex_replace', '(.*)', 'http://\\1:2379')|join(',') }}"
POD_NETWORK: 10.3.0.0/24
SERVICE_IP_RANGE: 10.4.0.0/24
K8S_SERVICE_IP: 10.4.0.1
DNS_SERVICE: 10.3.0.10

ADVERTISE_IP: "{{ ansible_default_ipv4.address }}"