MASTER_HOST: "{{ groups.masters[0] }}"
ETCD_ENDPOINTS: "{{ groups.masters|map('regex_replace', '(.*)', 'http://\\1:2379')|join(',') }}"
POD_NETWORK: 10.3.0.0/24
SERVICE_IP_RANGE: 10.4.0.0/24
K8S_SERVICE_IP: 10.4.0.1
DNS_SERVICE_IP: 10.3.0.10

ETCD_SERVER: "{{ ETCD_ENDPOINTS.split(',')[0] }}"
K8S_VER: v1.6.1_coreos.0
NETWORK_PLUGIN: cni

is_master: "{{ 'masters' in group_names }}"

hostvars2: "{{ hostvars }}" # Some weird bug where hostvars is not available for json_query

coreos_nodes: "{{ hostvars2 | json_query('*.{ip: ansible_host, name: inventory_hostname}') }}"
node: {ip: "{{ ansible_host }}", "name": "{{ inventory_hostname }}"}

ADVERTISE_IP: "{{ node.ip }}"
