hostvars2: "{{ hostvars }}" # Some weird bug where hostvars is not available for json_query

etcd_nodes: "{{ hostvars2 | json_query('* | [?contains(group_names, `etcd`)].{ip: ansible_host, name: inventory_hostname}') }}"
MASTER_HOST: "{{ groups.masters | default([None]) | first }}"
ETCD_ENDPOINTS: "{{ etcd_nodes | json_query('[].join(``, [`http://`, ip, `:2379`]) | join(`,`, @)') }}"
POD_NETWORK: 10.3.0.0/24
SERVICE_IP_RANGE: 10.4.0.0/24
K8S_SERVICE_IP: 10.4.0.1
DNS_SERVICE_IP: 10.3.0.10

ETCD_SERVER: "{{ ETCD_ENDPOINTS.split(',')[0] }}"
K8S_VER: v1.9.0_coreos.0
NETWORK_PLUGIN: cni

is_master: "{{ 'masters' in group_names }}"


coreos_nodes: "{{ hostvars2 | json_query('*.{ip: ansible_host, name: inventory_hostname}') }}"
node: {ip: "{{ ansible_host }}", "name": "{{ inventory_hostname }}"}
use_calico: no

ADVERTISE_IP: "{{ node.ip }}"
