- hosts: localhost
  vars:
    dist: "dist"
  tasks:
  - get_url:
      url: "https://raw.githubusercontent.com/coreos/scripts/master/contrib/create-coreos-vdi"
      dest: "{{ dist }}/create-coreos-vdi"
      mode: 0755
      force: yes

  - command: "{{ dist }}/create-coreos-vdi -d dist -V stable"
    args:
      creates: "{{ dist }}/coreos_production_*.vdi"

  - file:
      path: "{{ dist }}/configdrive/openstack/latest"
      state: directory
      recurse: yes

  - template:
      src: ./cloud-config.j2.yml
      dest: "{{ dist }}/configdrive/openstack/latest/user_data"

  - file:
      src: "configdrive/openstack/latest/user_data"
      dest: "{{ dist }}/cloud-config.yml"
      state: link

  - command: "mkisofs -R -V config-2 -o {{dist}}/configdrive.iso {{ dist }}/configdrive"
