- file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  with_items:
  - /etc/kubernetes/manifests

- template:
    src: "{{ item }}.yaml"
    dest: "/etc/kubernetes/manifests/{{ item }}.yaml"
  notify:
  - restart kubelet
  with_items:
  - kube-controller-manager
  - kube-proxy
  - kube-scheduler

- template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  notify:
  - restart kubelet
  with_items:
  - src: kubelet.service.j2
    dest: /etc/systemd/system/kubelet.service
