- file:
    path: /etc/systemd/system/etcd2.service.d
    state: directory
    recurse: yes

- template:
    src: "01-cluster-config.conf.j2"
    dest: "/etc/systemd/system/etcd2.service.d/01-cluster-config.conf"
  register: etcd2_service

- systemd:
    daemon_reload: yes
    name: etcd2
    state: restarted
    enabled: yes
  when: etcd2_service.changed
