- file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  with_items:
  - /etc/flannel
  - /etc/systemd/system/flanneld.service.d/
  - /etc/systemd/system/docker.service.d/
  - /etc/kubernetes/cni
  - /etc/kubernetes/cni/net.d

- file:
    path: "{{ item.dest }}"
    state: "{{ item.state }}"
  notify:
  - restart flanneld
  - restart docker
  when: use_calico
  with_items:
  - dest: /etc/kubernetes/cni/net.d/10-flannel.conf
    state: absent

- template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  when: "{{ item.get('enabled', True) }}"
  notify:
  - restart flanneld
  with_items:
  - src: options.env.j2
    dest: /etc/flannel/options.env

  - src: 40-ExecStartPre-symlink.conf.j2
    dest: /etc/systemd/system/flanneld.service.d/40-ExecStartPre-symlink.conf

  - src: 40-flannel.conf.j2
    dest: /etc/systemd/system/docker.service.d/40-flannel.conf

  - src: docker_opts_cni.env.j2
    dest: /etc/kubernetes/cni/docker_opts_cni.env

  - src: 10-flannel.conf.j2
    dest: /etc/kubernetes/cni/net.d/10-flannel.conf
    enabled: "{{ not use_calico }}"
