- import_role: name=kubelet

- template:
    src: "kubelet/{{ item }}.yaml"
    dest: "/etc/kubernetes/manifests/{{ item }}.yaml"
  notify:
  - restart kubelet
  with_items:
  - kube-proxy

- template:
    src: "kubelet/{{ item }}.yaml"
    dest: "/etc/kubernetes/{{ item }}.yaml"
  notify:
  - restart kubelet
  with_items:
  - worker-kubeconfig

- template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  notify:
  - restart kubelet
  with_items:
  - src: kubelet/kubelet.service.j2
    dest: /etc/systemd/system/kubelet.service