- import_role: name=kubelet

- template:
    src: "kubelet/{{ item }}.yaml"
    dest: "/etc/kubernetes/manifests/{{ item }}.yaml"
  notify:
  - restart kubelet
  with_items:
  - kube-apiserver
  - calico