- import_role: name=kubelet

- template:
    src: "kubelet/{{ item }}.yaml"
    dest: "/etc/kubernetes/manifests/{{ item }}.yaml"
  notify:
  - restart kubelet
  with_items:
  - kube-apiserver
  - kube-proxy
  - kube-scheduler
  - kube-controller-manager

- template:
    src: "kubelet/{{ item }}.yaml"
    dest: "/etc/kubernetes/manifests/{{ item }}.yaml"
  notify:
  - restart kubelet
  when: use_calico
  with_items:
  - calico

- file:
    path: "{{ item }}"
    state: "absent"
  notify:
  - restart kubelet
  when: not use_calico
  with_items:
  - calico

- template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  notify:
  - restart kubelet
  with_items:
  - src: kubelet/kubelet.service.j2
    dest: /etc/systemd/system/kubelet.service