- file:
    path: /etc/kubernetes/ssl
    state: directory
    recurse: yes

- copy:
    dest: /etc/kubernetes/ssl/
    src: "./ssl/{{ item }}"
    owner: root
    group: root
    mode: 0600
  with_items:
  - ca.pem
  - apiserver.pem
  - apiserver-key.pem